name: pantry_chef
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  get_it: ^7.2.0
  dio: ^5.0.0  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.5
  share_plus: ^10.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.19.0
  flutter_lints: ^4.0.0
  build_runner: ^2.0.0
  hive_generator: ^2.0.0
  json_serializable: ^6.0.0
flutter:
  uses-material-design: true
